'use strict';

const { JiraClient } = require('../jira/client');
const { GitHubClient } = require('../github/client');
const { ClaudeClient } = require('../claude/client');
const { generateTests } = require('../claude/testGenerator');
const { generateFix } = require('../claude/fixGenerator');
const { runTests } = require('./testRunner');
const { buildRepoTree } = require('./repoTree');
const gitUtils = require('../utils/git');
const { applyFileOps } = require('../utils/fs');
const { branchNameForIssue, prTitleForIssue, prBodyForIssue } = require('../github/repo');
const { createLogger } = require('../utils/logger');

class Orchestrator {
  constructor(config) {
    this.config = config;
    this.logger = createLogger(config.logLevel);
    this.jira = new JiraClient(config.jira);
    this.github = new GitHubClient(config.github);
    this.claude = new ClaudeClient(config.anthropic);
  }

  /** Fetches assigned bugs and attempts a fix for each one, sequentially. */
  async runAll({ maxIssues } = {}) {
    const issues = await this.jira.fetchAssignedBugs({ maxResults: maxIssues ?? 20 });
    this.logger.info(`Fetched ${issues.length} candidate issue(s) from JIRA.`);

    const results = [];
    for (const issue of issues) {
      if (issue.labels.includes(this.config.jira.processedLabel)) {
        this.logger.info(`Skipping ${issue.key} — already attempted.`);
        continue;
      }
      results.push(await this.runOne(issue.key).catch((err) => {
        this.logger.error(`Failed on ${issue.key}: ${err.message}`);
        return { issueKey: issue.key, status: 'error', error: err.message };
      }));
    }
    return results;
  }

  /** Runs the full fix loop for a single JIRA issue key. */
  async runOne(issueKey) {
    const { logger, config } = this;
    logger.info(`\n=== ${issueKey} ===`);

    const issue = await this.jira.getIssue(issueKey);
    const git = await gitUtils.ensureRepo({
      owner: config.github.owner,
      repo: config.github.repo,
      token: config.github.token,
      dir: config.workspace.dir,
      baseBranch: config.github.baseBranch,
    });

    const branchName = branchNameForIssue(issue.key);
    await gitUtils.createBranch(git, branchName);
    logger.info(`Created branch ${branchName}`);

    const repoTree = await buildRepoTree(config.workspace.dir);

    logger.info('Generating reproduction test(s) with Claude...');
    const { testFiles } = await generateTests({
      claude: this.claude,
      issue,
      repoTree,
      workspaceDir: config.workspace.dir,
      logger,
    });
    await applyFileOps(config.workspace.dir, testFiles.map((f) => ({ ...f, action: 'write' })));
    logger.success(`Wrote ${testFiles.length} test file(s).`);

    let iteration = 0;
    let testResult = await runTests({
      testCommand: config.agent.testCommand,
      workspaceDir: config.workspace.dir,
    });
    let previousAttempt = null;
    let fixFiles = [];

    while (!testResult.passed && iteration < config.agent.maxIterations) {
      iteration += 1;
      logger.warn(`Tests failing (iteration ${iteration}/${config.agent.maxIterations}). Asking Claude for a fix...`);

      const fix = await generateFix({
        claude: this.claude,
        issue,
        testOutput: testResult.output,
        workspaceDir: config.workspace.dir,
        previousAttempt,
        logger,
      });
      fixFiles = fix.fixFiles;
      previousAttempt = fix;

      await applyFileOps(config.workspace.dir, fixFiles);
      logger.info(`Applied ${fixFiles.length} file change(s): ${fixFiles.map((f) => f.path).join(', ')}`);

      testResult = await runTests({
        testCommand: config.agent.testCommand,
        workspaceDir: config.workspace.dir,
      });
    }

    if (!testResult.passed) {
      logger.error(`Gave up on ${issue.key} after ${iteration} iteration(s). Tests still failing.`);
      await this.jira.addComment(
        issue.key,
        `phantom-bug-fixer attempted this ticket but could not get tests passing after ${iteration} iterations. Manual intervention required.`
      ).catch(() => {});
      await this.jira.addLabel(issue.key, config.jira.processedLabel).catch(() => {});
      return { issueKey: issue.key, status: 'failed', iterations: iteration };
    }

    logger.success(`Tests passing after ${iteration} iteration(s).`);

    if (config.agent.dryRun) {
      logger.info('DRY_RUN enabled — skipping commit/push/PR.');
      return { issueKey: issue.key, status: 'dry-run', iterations: iteration };
    }

    const committed = await gitUtils.commitAll(
      git,
      `fix(${issue.key}): ${issue.summary}\n\nAuto-generated by phantom-bug-fixer.`
    );
    if (!committed) {
      logger.warn('No file changes to commit — nothing to open a PR for.');
      return { issueKey: issue.key, status: 'no-changes', iterations: iteration };
    }

    await gitUtils.pushBranch(git, branchName);
    logger.success(`Pushed ${branchName}`);

    const pr = await this.github.createPullRequest({
      head: branchName,
      base: config.github.baseBranch,
      title: prTitleForIssue(issue),
      body: prBodyForIssue({
        issue,
        summary: previousAttempt?.reasoning,
        testFiles: testFiles.map((f) => f.path),
        fixFiles: fixFiles.map((f) => f.path),
        iterations: iteration,
      }),
    });
    logger.success(`Opened PR #${pr.number}: ${pr.html_url}`);

    await this.jira.addComment(
      issue.key,
      `phantom-bug-fixer opened a fix: ${pr.html_url}`
    ).catch(() => {});
    await this.jira.addLabel(issue.key, config.jira.processedLabel).catch(() => {});

    return { issueKey: issue.key, status: 'pr-opened', prUrl: pr.html_url, iterations: iteration };
  }
}

module.exports = { Orchestrator };
